version: '2'
services:
  geoserver:
    image: dimasciput/haitidata_geoserver
    stdin_open: true
    external_links:
    - postgis:postgis
    tty: true
    ports:
    - 32208:8080/tcp
    labels:
      io.rancher.container.pull_image: always
  postgis:
    build: ./db
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASS: docker
  django:
    build: ./django_haitadata
    external_links:
    - postgis:postgis
    tty: true
    ports:
    - 33208:8080/tcp